name: testENV args

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'


env:
  ROOT_REPO_DIR: xxxx
  TZ: Asia/Shanghai
  FEEDS_CONF: $ROOT_REPO_DIR/compile/feeds.conf/feeds.conf.default




jobs:
  build:
    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: gen feeds and config
      env:
        ENV_ARG: "${FEEDS_CONF}"
      run : |
        MODEL_NAME="${FEEDS_CONF}"
        MODEL_NAME="$(basename "$MODEL_NAME")"
        echo "[INFO] test $FEEDS_CONF"
        echo "[INFO] MODEL_NAME=$MODEL_NAME"
        echo "[INFO] ENV_ARG=$ENV_ARG"

#   echo结果: $ROOT_REPO_DIR/compile/feeds.conf/feeds.conf.default
#   env 中 无法使用 $env. 
